import { useEffect, useId, useRef, useState } from 'react';
import { CloudSun, Ellipsis, MapPin, Pin, RotateCcw } from 'lucide-react';
import type { PlanMetric, TrainingPlanDashboardData, WorkoutBlock, WorkoutSource } from './types';

const cardClass = 'rounded-[22px] border border-[#d7e3da] bg-white shadow-[0_14px_35px_rgba(23,37,31,0.06)]';

export function PlanBreadcrumb({ items }: { items: string[] }) {
  return <nav aria-label="計畫麵包屑" className="flex flex-wrap items-center gap-2 text-xs font-bold tracking-[0.12em] text-[#0e6245]">{items.map((item, index) => <span key={item} className="flex items-center gap-2">{index > 0 && <span aria-hidden="true">•</span>}<span>{item}</span></span>)}</nav>;
}

export function PlanProgressRing({ progress }: Pick<TrainingPlanDashboardData, 'progress'>) {
  const [value, setValue] = useState(0); const radius = 42; const circumference = 2 * Math.PI * radius;
  useEffect(() => { const frame = requestAnimationFrame(() => setValue(progress.percentage)); return () => cancelAnimationFrame(frame); }, [progress.percentage]);
  return <div className="relative grid h-28 w-28 shrink-0 place-items-center" role="img" aria-label={`${progress.label} ${progress.percentage}%`}><svg className="-rotate-90" width="112" height="112" aria-hidden="true"><circle cx="56" cy="56" r={radius} fill="none" stroke="#e4ece6" strokeWidth="9"/><circle cx="56" cy="56" r={radius} fill="none" stroke="#0e6245" strokeWidth="9" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={circumference * (1 - value / 100)} className="transition-[stroke-dashoffset] duration-1000 ease-out"/></svg><div className="absolute text-center"><div className="text-2xl font-extrabold tabular-nums text-[#17251f]">{value}%</div><div className="text-[10px] font-bold text-[#65746b]">{progress.current} / {progress.total} 週</div></div></div>;
}

export function PlanHero({ data }: { data: TrainingPlanDashboardData }) {
  return <section aria-labelledby="plan-title" className="flex flex-col justify-between gap-7"><div className="space-y-6"><PlanBreadcrumb items={data.breadcrumb}/><div><h1 id="plan-title" className="text-5xl font-black leading-none tracking-[-0.06em] text-[#17251f] sm:text-6xl lg:text-[72px]">{data.planName}</h1><p className="mt-3 text-base font-bold text-[#0e6245] sm:text-lg">{data.weekLabel}</p></div></div><div className="flex items-center gap-5 border-t border-[#dbe4dd] pt-5"><PlanProgressRing progress={data.progress}/><p className="max-w-xs text-sm leading-6 text-[#536259]">{data.copy.progressSummary}</p></div></section>;
}

export function PlanMetricCard({ metric }: { metric: PlanMetric }) {
  return <article className="min-w-0 border-l border-[#dbe4dd] pl-5 first:border-l-0 first:pl-0 transition-transform duration-200 hover:-translate-y-0.5"><p className="text-sm font-bold text-[#557066]">{metric.label}</p><p className="mt-2 text-2xl font-extrabold tracking-tight text-[#17251f]">{metric.value}</p><p className="mt-1.5 text-sm leading-6 text-[#617168]">{metric.detail}</p></article>;
}
export function PlanMetricsGrid({ metrics }: { metrics: PlanMetric[] }) { return <div className="grid gap-5 border-t border-[#dbe4dd] pt-5 sm:grid-cols-3">{metrics.map((metric) => <PlanMetricCard key={metric.label} metric={metric}/>)}</div>; }

export function WorkoutSourceTabs({ selected, onChange, labels }: { selected: WorkoutSource; onChange: (source: WorkoutSource) => void; labels: TrainingPlanDashboardData['copy']['tabs'] }) {
  const tabs: { id: WorkoutSource; label: string }[] = [{ id: 'coach', label: labels.coach }, { id: 'schedule', label: labels.schedule }];
  return <div className="flex gap-1 rounded-full bg-[#f4f7f4] p-1" role="tablist" aria-label="課表來源">{tabs.map((tab) => <button key={tab.id} role="tab" aria-selected={selected === tab.id} onClick={() => onChange(tab.id)} className={`rounded-full px-3 py-1.5 text-xs font-bold transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0e6245] ${selected === tab.id ? 'bg-white text-[#0e6245] shadow-sm' : 'text-[#66756c] hover:text-[#17251f]'}`}>{tab.label}</button>)}</div>;
}
export function WeatherAlert({ summary, advisory }: TrainingPlanDashboardData['workout']['weather']) { return <aside className="rounded-xl border border-[#f4cda9] bg-[#fff2e7] px-4 py-3 text-sm text-[#9a4a16]" aria-label="天氣提醒"><div className="flex gap-2"><CloudSun className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><div><p className="font-bold">{summary}</p><p className="mt-0.5 text-xs font-semibold">{advisory}</p></div></div></aside>; }
export function WorkoutSideMetric({ block }: { block: WorkoutBlock }) { return <div className="rounded-2xl bg-[#faf9f5] px-4 py-3"><p className="font-bold text-[#26382f]">{block.label}</p><p className="mt-1 text-sm text-[#68766e]">{block.detail}</p></div>; }
export function MainWorkoutCard({ block }: { block: WorkoutBlock }) { return <article className="rounded-2xl border border-[#b9d8c6] border-l-4 border-l-[#26805a] bg-[#fbfefa] px-4 py-3"><p className="font-bold text-[#0e6245]">{block.label}</p><p className="mt-2 text-sm leading-6 text-[#5b6c62]">{block.detail}</p></article>; }
export function ViewTodayWorkoutButton({ label }: { label: string }) { return <a href="/training/today" className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#0e6245] px-5 text-sm font-bold text-white transition duration-200 hover:-translate-y-px hover:shadow-[0_8px_18px_rgba(14,98,69,0.24)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0e6245]"><Pin className="h-4 w-4" aria-hidden="true"/>{label}</a>; }

function MoreMenu({ label, items }: { label: string; items: TrainingPlanDashboardData['copy']['moreItems'] }) {
  const [open, setOpen] = useState(false); const id = useId(); const button = useRef<HTMLButtonElement>(null);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { setOpen(false); button.current?.focus(); } }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, []);
  return <div className="relative"><button ref={button} type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls={id} aria-label={label} className="rounded-lg p-2 text-[#526359] hover:bg-[#f1f5f1] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0e6245]"><Ellipsis className="h-5 w-5"/></button>{open && <div id={id} role="menu" className="absolute right-0 z-10 mt-1 w-36 rounded-xl border border-[#d7e3da] bg-white p-1 shadow-lg">{items.map((item) => <a key={item.href} role="menuitem" href={item.href} className="block rounded-lg px-3 py-2 text-sm text-[#26382f] hover:bg-[#f2f7f3]">{item.label}</a>)}</div>}</div>;
}

export function TodayWorkoutPanel({ workout, copy }: Pick<TrainingPlanDashboardData, 'workout' | 'copy'>) {
  const [source, setSource] = useState<WorkoutSource>('coach'); const main = workout.blocks.find((block) => block.emphasis === 'main'); const supporting = workout.blocks.filter((block) => block.emphasis !== 'main');
  return <section aria-labelledby="today-workout-title" className={`${cardClass} p-5 sm:p-6`}><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-xs font-extrabold tracking-[0.1em] text-[#216844]">{workout.dateLabel}</p><div className="mt-3 flex flex-wrap items-center gap-3"><WorkoutSourceTabs selected={source} onChange={setSource} labels={copy.tabs}/><h2 id="today-workout-title" className="text-lg font-extrabold text-[#17251f]">{workout.title}</h2></div><p className="mt-2 text-sm text-[#627168]">{workout.subtitle}</p></div><MoreMenu label={copy.moreLabel} items={copy.moreItems}/></div><WeatherAlert {...workout.weather}/><div className="mt-4 grid gap-3 sm:grid-cols-[minmax(0,1.6fr)_minmax(160px,0.8fr)]">{main && <MainWorkoutCard block={main}/>}<div className="grid gap-3">{supporting.map((block) => <WorkoutSideMetric key={block.label} block={block}/>)}</div></div><div className="mt-4"><ViewTodayWorkoutButton label={copy.todayAction}/></div></section>;
}

export function PlanOverviewSection({ data }: { data: TrainingPlanDashboardData }) { return <section className="mx-auto max-w-[1440px] rounded-[28px] border border-[#d8e3dc] bg-[linear-gradient(118deg,#edf6ef_0%,#fffdf9_53%,#fff8df_100%)] p-5 shadow-[0_24px_55px_rgba(23,37,31,0.07)] sm:p-8 lg:p-11"><div className="grid gap-8 lg:grid-cols-[minmax(0,58fr)_minmax(360px,42fr)] lg:gap-12"><div className="flex min-w-0 flex-col gap-9"><PlanHero data={data}/><PlanMetricsGrid metrics={data.metrics}/></div><TodayWorkoutPanel workout={data.workout} copy={data.copy}/></div></section>; }
export function PlanDashboard({ data }: { data: TrainingPlanDashboardData }) { const embedded = Boolean(document.getElementById('training-dashboard-root')); return <div className={`${embedded ? '' : 'min-h-screen '}bg-[#f7f8f4] ${embedded ? '' : 'px-3 py-4 sm:px-6 sm:py-8 lg:px-10 '}text-[#17251f]`}><PlanOverviewSection data={data}/>{data.copy.apiNotice && <footer className="mx-auto flex max-w-[1440px] items-center gap-2 px-3 pt-4 text-xs text-[#68766e]"><MapPin className="h-3.5 w-3.5"/>{data.copy.apiNotice}</footer>}</div>; }
export function DashboardStatus({ state, message, onRetry }: { state: 'loading' | 'empty' | 'error'; message?: string; onRetry?: () => void }) { const labels = { loading: '正在載入你的訓練計畫…', empty: '尚未建立訓練計畫', error: message ?? '載入失敗' }; return <main className="grid min-h-screen place-items-center bg-[#f7f8f4] p-6"><section className={`${cardClass} max-w-md p-8 text-center`} aria-live="polite"><p className="text-lg font-extrabold text-[#17251f]">{labels[state]}</p><p className="mt-2 text-sm leading-6 text-[#627168]">{state === 'empty' ? '建立目標與週期後，這裡會顯示你的每日課表。' : state === 'error' ? '請確認連線後重試。' : '正在整理課表、天氣與訓練指標。'}</p>{state !== 'loading' && <button onClick={onRetry} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#0e6245] px-4 py-2.5 text-sm font-bold text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0e6245]"><RotateCcw className="h-4 w-4"/>重新載入</button>}</section></main>; }
